In [10]:
import numpy as np

In [11]:
my_list1 = [1,2,3,4]

In [38]:
my_list1

[1, 2, 3, 4]

In [12]:
my_array1 = np.array(my_list1)

In [13]:
my_array1

array([1, 2, 3, 4])

In [14]:
my_list2 = [11,22,33,44]

In [15]:
my_lists = [my_list1,my_list2]

In [16]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [17]:
my_arrays = np.array(my_lists)

In [18]:
my_arrays

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [19]:
my_arrays.shape

(2, 4)

In [20]:
my_arrays.dtype

dtype('int64')

In [22]:
my_zeros = np.zeros(5)

In [23]:
my_zeros.dtype

dtype('float64')

In [33]:
np.ones([2,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [34]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [35]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [37]:
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])