In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [9]:
A= np.random.randn(10)
A

array([-1.70703702, -0.20393293, -1.79283057,  0.43443113,  1.89934325,
       -0.52131846,  0.79298933, -0.97651517,  1.03675446,  0.38872624])

In [10]:
B = np.random.randn(10)
B

array([-1.77190868, -0.65069554, -0.25321074, -0.49472717, -0.27574743,
       -0.93819703,  0.3427467 ,  0.87701571,  0.47965763, -1.27373088])

In [11]:
np.add(A,B)

array([-3.4789457 , -0.85462847, -2.04604131, -0.06029603,  1.62359582,
       -1.45951549,  1.13573603, -0.09949945,  1.5164121 , -0.88500464])

In [17]:
min(np.minimum(A,B))

-1.7928305688260873

In [19]:
min(A)

-1.7928305688260873